name: rebase on push to main
on:
  push:
  release:
    types: [published]
jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event == 'release'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: "bbeesley/gha-auto-dependabot-rebase@v1.3.104"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
