name: Test on Pull Requests
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    concurrency: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn lint
      - name: commit linting changes
        uses: stefanzweifel/git-auto-commit-action@v4.13.0
        with:
          commit_message: ":robot: yarn lint [skip ci]"
      - run: yarn test
