name: Test on Pull Requests
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    concurrency: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - name: commit linting changes
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: ":robot: pnpm lint [skip ci]"
      - run: pnpm test
